#!/usr/bin/env python3
"""Generates Kubernetes manifests for the benchmark from the Compose file, so
the k3d run uses exactly the same services, images, config and fault
proxies. Writes bench/k8s/hotel.yaml.

Each Compose service becomes a Deployment and a Service with the same name,
so config.json and prometheus.yml work unchanged. LC_*
settings come from the ConfigMap lc-env (bench/k8s/run_k3d.sh replaces it
per run). Ports that the harness needs are exposed through k3d's load
balancer: frontend 5000 and Prometheus 9090.
"""
import os
import re

HERE = os.path.dirname(os.path.abspath(__file__))
HOTEL = os.path.join(HERE, "..", "hotel")

HOTEL_SVCS = {"frontend": 5000, "search": 8082, "geo": 8083, "rate": 8084, "profile": 8081,
              "recommendation": 8085, "user": 8086, "reservation": 8087}
EXPOSED = {"frontend": 5000, "prometheus": 9090}


def deployment(name, container):
    return f"""apiVersion: apps/v1
kind: Deployment
metadata: {{ name: {name}, labels: {{ app: {name} }} }}
spec:
  replicas: 1
  selector: {{ matchLabels: {{ app: {name} }} }}
  template:
    metadata: {{ labels: {{ app: {name} }} }}
    spec:
      enableServiceLinks: false
      containers:
{container}
"""


def service(name, ports, lb=False):
    plist = "\n".join(f"    - {{ name: p{p}, port: {p}, targetPort: {p} }}" for p in ports)
    t = "LoadBalancer" if lb else "ClusterIP"
    return f"""apiVersion: v1
kind: Service
metadata: {{ name: {name} }}
spec:
  type: {t}
  selector: {{ app: {name} }}
  ports:
{plist}
"""


def hotel(name, port):
    svc = "frontend" if name == "frontend" else "srv-" + name
    c = f"""        - name: {name}
          image: loadcontrol/hotel:latest
          imagePullPolicy: Never
          command: [ "{name}" ]
          envFrom: [ {{ configMapRef: {{ name: lc-env }} }} ]
          env:
            - {{ name: LC_SERVICE, value: {svc} }}
            - {{ name: JAEGER_SAMPLE_RATIO, value: "0.01" }}
            - {{ name: LOG_LEVEL, value: error }}
            - {{ name: MEMC_TIMEOUT, value: "10" }}
          volumeMounts: [ {{ name: cfg, mountPath: /workspace/config.json, subPath: config.json }} ]
      volumes: [ {{ name: cfg, configMap: {{ name: hotel-config }} }} ]"""
    return deployment(name, c) + "---\n" + service(name, [port, 9100], lb=name in EXPOSED)


def simple(name, image, ports, args=None, mounts=""):
    a = f"\n          args: {args}" if args else ""
    c = f"""        - name: {name}
          image: {image}{a}{mounts}"""
    return deployment(name, c) + "---\n" + service(name, ports, lb=name in EXPOSED)


def configmap(name, files):
    body = "\n".join(f"  {k}: |\n" + "".join("    " + l + "\n" for l in v.splitlines()) for k, v in files.items())
    return f"apiVersion: v1\nkind: ConfigMap\nmetadata: {{ name: {name} }}\ndata:\n{body}"


def main():
    docs = []
    read = lambda f: open(os.path.join(HOTEL, f)).read()
    docs.append(configmap("hotel-config", {"config.json": read("config.json")}))
    docs.append(configmap("prometheus-config", {"prometheus.yml": read("prometheus.yml")}))
    docs.append("apiVersion: v1\nkind: ConfigMap\nmetadata: { name: lc-env }\ndata: {}\n")
    docs.append(simple("consul", "hashicorp/consul:1.20", [8500, 8600]))
    docs.append(simple("jaeger", "jaegertracing/all-in-one:1.62.0", [16686, 6831]))
    # Each cache pod carries a tc sidecar with NET_ADMIN so netem faults can
    # be injected into the pod's network namespace, as on Compose.
    tc_sidecar = """
        - name: tc
          image: loadcontrol/tc:latest
          imagePullPolicy: Never
          command: [ "sleep", "infinity" ]
          securityContext: { capabilities: { add: [ "NET_ADMIN" ] } }"""
    for m in ["rate", "profile", "reserve"]:
        docs.append(simple(f"memcached-{m}", "memcached:1.6", [11211], '[ "-m", "128", "-t", "2" ]', tc_sidecar))
    for m in ["geo", "profile", "rate", "recommendation", "reservation", "user"]:
        docs.append(simple(f"mongodb-{m}", "mongo:5.0", [27017], '[ "--wiredTigerCacheSizeGB", "0.25", "--quiet" ]'))
    prom_mount = """
          volumeMounts: [ { name: cfg, mountPath: /etc/prometheus/prometheus.yml, subPath: prometheus.yml } ]
      volumes: [ { name: cfg, configMap: { name: prometheus-config } } ]"""
    docs.append(simple("prometheus", "prom/prometheus:v3.0.1", [9090], None, prom_mount))
    for n, p in HOTEL_SVCS.items():
        docs.append(hotel(n, p))
    with open(os.path.join(HERE, "hotel.yaml"), "w", newline="
") as f:
        f.write("# Generated by bench/k8s/gen.py from bench/hotel. Do not edit.\n")
        f.write("\n---\n".join(d.strip() + "\n" for d in docs))


if __name__ == "__main__":
    main()
